import Link from 'next/link'
import { ArrowRight, ArrowUpRight, BarChart3, BatteryCharging, Bolt, Gauge, RadioTower, Zap } from 'lucide-react'
import { Reveal } from '@/components/reveal'

const benefits = [
  { icon: Gauge, title: 'Know your baseline', text: 'Turn fragmented meter data into one clear picture of how your sites perform.' },
  { icon: Bolt, title: 'Move with certainty', text: 'Surface anomalies and opportunities that deserve attention, automatically.' },
  { icon: BarChart3, title: 'Prove the impact', text: 'Track every intervention from first insight to measurable savings.' },
]
const products = [
  { label: '01 / Monitor', title: 'One view of every site.', text: 'Live energy intelligence for the places that matter most.', icon: RadioTower },
  { label: '02 / Optimize', title: 'Find the signal in the noise.', text: 'AI-assisted insights that turn complex data into clear action.', icon: BatteryCharging },
  { label: '03 / Prove', title: 'Make progress measurable.', text: 'Connect every intervention to the outcomes your operation cares about.', icon: BarChart3 },
]

export default function Home() {
  return <main>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow hero-eyebrow">Energy, in focus <span className="pulse-dot" /></p><h1>Make energy<br /><em>work harder.</em></h1><p className="hero-lede">Gridline is the intelligence layer for energy-intensive operations. See what is happening, understand why, and make your next move count.</p><div className="hero-actions"><Link href="/contact" className="button button-accent">See the platform <ArrowUpRight size={16} /></Link><Link href="/products" className="text-link">Explore capabilities <ArrowRight size={16} /></Link></div></div><div className="hero-visual"><div className="orbital orbital-one" /><div className="orbital orbital-two" /><div className="hero-orb"><span className="orb-label">Live system status</span><strong>98.4<span>%</span></strong><small>assets connected</small><div className="orb-bars"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="hero-tag tag-one"><span className="mini-dot green" />Peak load down <b>12.8%</b></div><div className="hero-tag tag-two"><span className="mini-dot orange" />3 sites need review</div></div></div><div className="hero-footer container"><span>Trusted by teams building a more efficient world</span><div className="logo-row"><span>NORTHSTAR</span><span>VANTAGE</span><span>cohere</span><span>FIELDWORK</span></div></div></section>

    <section className="section intro-section"><div className="container intro-grid"><Reveal><p className="eyebrow">The clearer path forward</p><h2>Complex systems.<br /><em>Simple decisions.</em></h2></Reveal><Reveal delay={.12}><p className="intro-text">Energy is too important to be managed in the dark. We bring operational data together, make it legible, and help your team act before small inefficiencies become expensive problems.</p><Link href="/about" className="text-link">Why Gridline <ArrowRight size={16} /></Link></Reveal></div>
      <div className="container benefit-grid">{benefits.map((b, i) => <Reveal key={b.title} delay={i * .1}><article className="benefit-card"><b.icon size={22} strokeWidth={1.5} /><h3>{b.title}</h3><p>{b.text}</p></article></Reveal>)}</div>
    </section>

    <section className="section platform-showcase"><div className="container"><div className="section-heading"><div><p className="eyebrow">The Gridline platform</p><h2>From raw data to<br /><em>real direction.</em></h2></div><p>One connected view for the people who keep your operation moving.</p></div><div className="platform-stage"><div className="platform-stage-copy"><span className="stage-kicker"><Zap size={14} /> Live intelligence layer</span><h3>See the story behind every kilowatt.</h3><p>Gridline brings meters, assets, and teams into the same operating picture, so your next decision starts with context—not guesswork.</p><Link href="/products" className="text-link">Explore the platform <ArrowRight size={16} /></Link></div><div className="dashboard-card" aria-label="Gridline energy performance dashboard"><div className="dashboard-top"><div><span className="dash-label">Portfolio performance</span><strong>84.6 <small>/ 100</small></strong></div><span className="status-pill"><i /> On track</span></div><div className="chart-wrap"><div className="chart-y"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="chart"><div className="chart-grid" /><svg viewBox="0 0 460 150" role="img" aria-label="Energy performance trending upward"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".28" /><stop offset="1" stopColor="currentColor" stopOpacity="0" /></linearGradient></defs><path d="M0 123 C35 116 52 119 78 105 S122 108 148 82 S192 94 218 67 S255 73 282 55 S325 62 348 38 S397 42 460 18 L460 150 L0 150Z" fill="url(#chartFill)" /><path d="M0 123 C35 116 52 119 78 105 S122 108 148 82 S192 94 218 67 S255 73 282 55 S325 62 348 38 S397 42 460 18" fill="none" stroke="currentColor" strokeWidth="3" /></svg><div className="chart-x"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Today</span></div></div></div><div className="dashboard-bottom"><div><span className="dash-label">Energy saved this month</span><strong>18.2%</strong></div><div><span className="dash-label">Active alerts</span><strong>03</strong></div><div><span className="dash-label">Sites online</span><strong>24/24</strong></div></div></div></div></div></section>

    <section className="section products-preview moves-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">One system. Three moves.</p><h2>Built for the work<br /><em>behind the numbers.</em></h2></div><div className="moves-intro"><span>01—03</span><p>One connected rhythm for every stage of better energy management.</p><Link href="/products" className="text-link">View all capabilities <ArrowRight size={16} /></Link></div></div><div className="product-preview-grid">{products.map((p, i) => <Reveal key={p.title} delay={i * .1}><article className="preview-card"><div className="preview-icon"><p>{p.label}</p><p.icon size={25} strokeWidth={1.4} /></div><h3>{p.title}</h3><p>{p.text}</p><Link href="/products" className="circle-link" aria-label={`Explore ${p.title}`}><ArrowUpRight size={18} /></Link></article></Reveal>)}</div></div></section>

    <section className="section cta-section"><div className="container cta-inner"><p className="eyebrow">Ready to see clearly?</p><h2>Make your next<br /><em>move count.</em></h2><Link href="/contact" className="button button-dark">Talk to the team <ArrowUpRight size={16} /></Link></div></section>
  </main>
}
